version: 2

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: develop

jobs:
  build:
    docker:
      - image: circleci/node:12.20

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - run:
          name: Run tests
          command: yarn run jest
      - run:
          name: Pretty check
          command: npm run prettier-check
      - run:
          name: Lint check
          command: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy-prod:
    docker:
      - image: circleci/node:12.20

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install awscli
          command: wget https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip && unzip awscli-exe-linux-x86_64.zip && sudo ./aws/install
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
      - run:
          name: Deploy application
          command: sls deploy --stage prod
      - run:
          name: Canary deployment prod
          command: bash ./canary.sh

  deploy-dev:
    docker:
      - image: circleci/node:12.20

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
      - run:
          name: Deploy application
          command: sls deploy --stage dev
